export const dashboard = <i className="fa-solid fa-chart-line"></i>
export const transactions = <i className="fa-solid fa-credit-card"></i>
export const trend = <i className="fa-solid fa-money-bill-trend-up"></i>
export const expenses = <i className="fa-solid fa-money-bill-transfer"></i>
export const signout = <i className="fa-solid fa-right-from-bracket"></i>
export const plus = <i className="fa-solid fa-plus"></i>
export const trash = <i className="fa-solid fa-trash"></i>
export const rupee = <i class="fa-solid fa-indian-rupee-sign"></i>
export const calendar = <i className="fa-solid fa-calendar-days"></i>
export const comment = <i className="fa-solid fa-comment"></i>
export const money = <i className="fa-solid fa-money-bill"></i>
export const bitcoin = <i className="fa-brands fa-bitcoin"></i>
export const piggy = <i className="fa-solid fa-piggy-bank"></i>
export const book = <i className="fa-solid fa-book"></i>
export const food = <i className="fa-solid fa-utensils"></i>
export const medical = <i className="fa-solid fa-notes-medical"></i>
export const tv = <i className="fa-solid fa-tv"></i>
export const clothing = <i className="fa-solid fa-shirt"></i>
export const location = <i className="fa-solid fa-location-dot"></i>
export const circle = <i className="fa-solid fa-circle"></i>
export const freelance = <i className="fa-solid fa-laptop"></i>
export const stocks = <i className="fa-solid fa-arrow-trend-up"></i>
export const users = <i className="fa-solid fa-users"></i>
export const takeaways = <i className="fa-solid fa-bag-shopping"></i>
export const groceries = <i className="fa-solid fa-bag-shopping"></i>
export const navToggler = <i className="fa-solid fa-bars"></i>
export const debt = <i className="fa-solid fa-sack-dollar"></i>

